language: node_js
node_js:
    - lts/*
dist: focal
cache:
    yarn: true
    directories:
        - node_modules

before_script:
  - cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

addons:
  postgresql: "13.0"