language: node_js
node_js:
    - lts/*
dist: focal
cache:
    yarn: true
    directories:
        - node_modules

before_script:
  - cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test < ./applauz_database/create.sql

services:
  - postgresql

# addons:
#   postgresql: "12.4"
#   apt:
#     packages:
#     - postgresql-12
#     - postgresql-client-12
env:
  global:
  - PGPORT=5433