version: '3.8'
services:
  applauz_express_backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: applauz_express_backend
    restart: unless-stopped
    volumes:
      - "/app/node_modules"
      - "./:/app"
    ports:
      - "3000:3000"
    networks:
      - applauz-backend
  applauz_db:
    image: postgres:13-alpine
    container_name: applauz_db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - applauz_db_data:/var/lib/postgresql/data
      - ./applauz_database/:/applauz_database/
    networks:
      - applauz-backend
      
networks:
  applauz-backend:
    driver: bridge

volumes:
  applauz_db_data:
    driver: local