version: '3.8'
services:
  applauz_express_backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: applauz_express_backend
    restart: unless-stopped
    volumes:
      - "/app/node_modules"
      - "./:/app"
    ports:
      - "3000:3000"
